name: Macos
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

jobs:
  Build:
    runs-on: macos-15
    if: github.repository_owner == 'myridia'

    steps:
      - name: Install Rust and Dependencies
        run: |
          brew install llvm tree pkg-config glib gobject-introspection openssl gtk+3
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          rustup target add x86_64-apple-darwin
          rustup component add llvm-tools-preview
          export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig"
          export PKG_CONFIG_ALLOW_CROSS=1
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
          export CC="/opt/homebrew/opt/llvm/bin/clang"
          export CXX="/opt/homebrew/opt/llvm/bin/clang++"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Native macOS (ARM64)
        run: |
          cargo build --release

      - name: Compile Intel macOS (x86_64)
        run: |
          export RUSTFLAGS="-C linker=/usr/bin/ld"
          cargo build --release --target x86_64-apple-darwin

      - name: List Compiled Binaries
        run: |
          cd target
          tree .

      - name: Prepare App Bundles and DMGs
        run: |
          # Native macOS (ARM64)
          mkdir -p autotext_macos.app/Contents/MacOS
          cp target/release/autotext autotext_macos.app/Contents/MacOS/autotext
          hdiutil create -volname "autotext_macos" -srcfolder "autotext_macos.app" -ov -format UDZO "autotext_macos.dmg"

          # Intel macOS (x86_64)
          mkdir -p autotext_macos_intel.app/Contents/MacOS
          cp target/x86_64-apple-darwin/release/autotext autotext_macos_intel.app/Contents/MacOS/autotext
          hdiutil create -volname "autotext_macos_intel" -srcfolder "autotext_macos_intel.app" -ov -format UDZO "autotext_macos_intel.dmg"

      - name: Release Intel
        if: github.repository_owner == 'myridiax' && github.ref_type == 'tag' && success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'autotext_macos_intel.dmg'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Release Silicon
        if: github.repository_owner == 'myridiax' && github.ref_type == 'tag' && success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'autotext_macos.dmg'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
