name: Windows
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  Build:
    runs-on: windows-latest
    if: github.repository_owner == 'myridia'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Rust          
        uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly 
          target: x86_64-pc-windows-gnu 


      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-pkg-config mingw-w64-x86_64-glib2 mingw-w64-ucrt-x86_64-gtk3 
     
      - name: Compile
        shell: msys2 {0}
        run: |       
          export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
          # echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8NoBOM -Append
          cargo build --release 
          # pacman -S mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-openssl           
          # cargo build --release --target x86_64-pc-windows-gnu 
          # cd target/x86_64-pc-windows-gnu/release/
          # dir 
           
      - name: Release
        if: github.repository_owner == 'myridiax'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/x86_64-pc-windows-gnu/release/autotext.exe'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


          

          


    
   


        


        


 
     
