name: Windows
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  Build:
    runs-on: windows-latest
    if: github.repository_owner == 'myridia'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Rust          
        uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly 
          target: x86_64-pc-windows-gnu 


      - name: MSYS2_Pacman
        run: |
          winget install --id=The.OpenGroup.base-containers.MinGW-W64-ucrt-x86_64 --accept-package-agreements --source winget
          $msys2_root = "C:\msys64" # Default installation path. Adjust if different.
          $env:PATH = "$msys2_root\usr\bin;$msys2_root\mingw64\bin;$env:PATH"
          # pacman -Syu --noconfirm mingw-w64-ucrt-x86_64-gtk3
          pacman -Syu --noconfirm mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-glib2 mingw-w64-ucrt-x86_64-openssl
          # pacman -S mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-openssl 

      - name: Build
        run: |          
          # pacman -S mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-openssl           
          # cargo build --release --target x86_64-pc-windows-gnu 
          # cd target/x86_64-pc-windows-gnu/release/
          dir 
           
      - name: Release
        if: github.repository_owner == 'myridiax'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/x86_64-pc-windows-gnu/release/autotext.exe'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


          

          


    
   


        


        


 
     
